spring.application.name=spring-boot-testing-practice

app.name=Student Management API
app.version=1.0
app.environment=development

logging.level.root=INFO
logging.level.com.example.spring_boot_testing_practice=DEBUG

spring.jpa.show-sql=true