spring.application.name=spring-boot-testing-practice

app.name=Student Management API
app.version=1.0
app.environment=production

logging.level.root=WARN
logging.level.com.example.spring_boot_testing_practice=INFO

spring.jpa.show-sql=false