spring.application.name=hibernate-advanced-mappings

spring.datasource.url=jdbc:postgresql://localhost:5432/hibernate_advanced_mappings
spring.datasource.username=postgres
spring.datasource.password=Sunny@0910

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true